name: Run Tests and Deploy Allure Report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Allure CLI
        run: |
          sudo apt update
          sudo apt install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      - name: Run Tests
        run: mvn clean test || true

      - name: Verificar archivos .txt/.png en target/allure-results
        run: |
          echo "🔍 Buscando attachments en target/allure-results"
          find target/allure-results -type f \( -name "*.txt" -o -name "*.png" \) -exec ls -lh {} \; || echo "❌ No se encontraron .txt ni .png en target/allure-results"

      - name: Mostrar contenido de target/allure-results/*.json
        run: |
          echo "🧪 Revisando JSONs:"
          for file in target/allure-results/*.json; do
            echo "📄 $file"
            grep -i attachment "$file" || echo "⚠️ No se encontró attachment en $file"
          done

      - name: Generate Allure Report
        run: allure generate target/allure-results --clean -o allure-report

      - name: Verificar contenido en allure-report
        run: |
          echo "📁 Contenido en allure-report/data/attachments:"
          ls -lh allure-report/data/attachments || echo "❌ No se encontraron archivos en allure-report/data/attachments"

      - name: Upload Allure Results as Artifact (opcional)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
